FAQ page
arunabh98/MI-2016 pull request #10
Opened 2016-11-26 13:00 UTC by TheFlash98

2016-11-26 15:44 UTC, arunabh98 requested changes

2016-11-26 15:44 UTC, Arunabh98 commented on app/src/main/res/layout/faqpage.xml
> +        />
Shift `/>` to the line above.

2016-11-26 15:51 UTC, Arunabh98 commented
@TheFlash98 could you rename `faqpage.xml` to `activity_faq.xml`. Also could you create a Activty file corresponding to this layout - `FaqActivity`.

2016-11-26 16:08 UTC, unstablebrainiac commented on app/src/main/res/layout/faqpage.xml
> +        />
We'll reformat the code occasionally, this shouldn't be a problem.

2016-11-26 16:13 UTC, unstablebrainiac commented
Instead of hardcoding strings, write them in the `strings.xml` file and use `@string` in `android:text` attribute

2016-11-26 16:15 UTC, nihal111 commented
Use Ctrl + Shift + Alt + L for code cleanup

2016-11-26 16:15 UTC, Arunabh98 commented on app/src/main/res/layout/faqpage.xml
> +        />
Yes you're right. But waise bhi he has to make other changes so he might as well do this.

2016-11-28 10:03 UTC, Arunabh98 commented
I tested it and I think this looks good!

2016-11-28 10:06 UTC, arunabh98 approved these changes

2016-11-28 10:35 UTC, unstablebrainiac commented
Can you replace the activity with a fragment so that it can be linked with the navigation drawer?

2016-11-28 19:54 UTC, merged